In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [8]:
np.ones((5,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [13]:
np.linspace(0,101,20)

array([   0.        ,    5.31578947,   10.63157895,   15.94736842,
         21.26315789,   26.57894737,   31.89473684,   37.21052632,
         42.52631579,   47.84210526,   53.15789474,   58.47368421,
         63.78947368,   69.10526316,   74.42105263,   79.73684211,
         85.05263158,   90.36842105,   95.68421053,  101.        ])

In [17]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [29]:
np.random.randn(400).sum()

-19.63182792691309